//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEMHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionMaster
    {
        public string PrescriptionId { get; set; }
        public string PrescriberName { get; set; }
        public int PhysicianId { get; set; }
        public string PatientName { get; set; }
        public string PatientId { get; set; }
        public string Diagnosis { get; set; }
        public string DrugName { get; set; }
        public string Dose { get; set; }
        public string DoseUnits { get; set; }
        public string Frequency { get; set; }
        public string NumOfDays { get; set; }
        public System.DateTime SubmitDate { get; set; }
        public System.DateTime ProcessedDate { get; set; }
        public string Allergies { get; set; }
        public string Comments { get; set; }
        public string Refills { get; set; }
        public string IssueTo { get; set; }
        public string PharmacyId { get; set; }
    
        public virtual PhysicianMaster PhysicianMaster { get; set; }
    }
}
