//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEMHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleMaster
    {
        public string TaskId { get; set; }
        public string Task { get; set; }
        public int PatientId { get; set; }
        public string PatientName { get; set; }
        public System.DateTime TaskDate { get; set; }
        public System.DateTime TaskDueDate { get; set; }
        public int PhysicianId { get; set; }
        public string PhysicianName { get; set; }
    
        public virtual PatientMaster PatientMaster { get; set; }
        public virtual PatientMaster PatientMaster1 { get; set; }
        public virtual PhysicianMaster PhysicianMaster { get; set; }
    }
}
